### ISSUE TITLE
saftlib 3.1.0: saftlib may hang up when activating multiple conditions with callback function

### ISSUE THREAD

**Issue by dietrichb** [GSI-CS-CO/saftlib#119]
It is possible to reproduce this issue when using the saft-uni tool with saftlib 3.1.0 on yocto. Sometimes, saftlib hangs up. It also not possible to check the saftlib status from another terminal window, using 'saft-ctl tr0 -ij' (this hangs also). Terminating the saft-uni process recovers saftlib.

I have the impression that this is caused, when some conditions are activated and callback functions are executed while the activation of the remaining conditions is not finished. Once all conditions are activated, everything runs as expected.  

This happens on Yocto.

Remark: This behaviour does NOT show up with the older saftlib version 2.5.0 on a ACC7 ramdisk. Here, everything runs without any trouble.

**Comment by miree** [comment]
please try branch "fix-saftbus-write-all"

**Comment by dietrichb** [comment]
I tried this branch, but it did not help; use workaround with 'sink->ToggleActive()' for now
