### ISSUE TITLE
FG warnings

### ISSUE THREAD

**Issue by alex-cscotg** [GSI-CS-CO/saftlib#21]
Could you please fix the following warnings?

git clone https://github.com/GSI-CS-CO/saftlib.git
git checkout c_release_giga_merge
./autogen
./configure
make

libtool: compile:  g++ -std=c++11 -DHAVE_CONFIG_H -I. -I.. -pthread -I/usr/include/giomm-2.4 -I/usr/lib/x86_64-linux-gnu/giomm-2.4/include -I/usr/include/glibmm-2.4 -I/usr/lib/x86_64-linux-gnu/glibmm-2.4/include -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/sigc++-2.0 -I/usr/lib/x86_64-linux-gnu/sigc++-2.0/include -I/usr/include/gio-unix-2.0/ -g -O2 -Wall -Wmissing-declarations -Wno-long-long -MT iOutputCondition.lo -MD -MP -MF .deps/iOutputCondition.Tpo -c iOutputCondition.cpp  -fPIC -DPIC -o .libs/iOutputCondition.o
iFunctionGenerator.cpp: In member function 'bool saftlib::iFunctionGenerator_Proxy::AppendParameterSet(const std::vector<short int>&, const std::vector<short int>&, const std::vector<int>&, const std::vector<unsigned char>&, const std::vector<unsigned char>&, const std::vector<unsigned char>&, const std::vector<unsigned char>&)':
iFunctionGenerator.cpp:95:36: warning: ignoring return value of 'int pipe(int*)', declared with attribute warn_unused_result [-Wunused-result]
   /*int r =*/ pipe(_vector_pipe_fd);
                                    ^
In file included from iFunctionGenerator.cpp:6:0:
iFunctionGenerator.h: In function 'void saftlib::write_vector_to_pipe(int, const T&) [with T = std::vector<short int>]':
iFunctionGenerator.h:176:3: warning: ignoring return value of 'ssize_t write(int, const void*, size_t)', declared with attribute warn_unused_result [-Wunused-result]
   write(fd, &size, sizeof(guint32));
   ^
iFunctionGenerator.h:177:3: warning: ignoring return value of 'ssize_t write(int, const void*, size_t)', declared with attribute warn_unused_result [-Wunused-result]
   write(fd, &std_vector[0], size*sizeof(decltype(std_vector.back())));
   ^
iFunctionGenerator.h: In function 'void saftlib::write_vector_to_pipe(int, const T&) [with T = std::vector<int>]':
iFunctionGenerator.h:176:3: warning: ignoring return value of 'ssize_t write(int, const void*, size_t)', declared with attribute warn_unused_result [-Wunused-result]
   write(fd, &size, sizeof(guint32));
   ^
iFunctionGenerator.h:177:3: warning: ignoring return value of 'ssize_t write(int, const void*, size_t)', declared with attribute warn_unused_result [-Wunused-result]
   write(fd, &std_vector[0], size*sizeof(decltype(std_vector.back())));
   ^
iFunctionGenerator.h: In function 'void saftlib::write_vector_to_pipe(int, const T&) [with T = std::vector<unsigned char>]':
iFunctionGenerator.h:176:3: warning: ignoring return value of 'ssize_t write(int, const void*, size_t)', declared with attribute warn_unused_result [-Wunused-result]
   write(fd, &size, sizeof(guint32));
   ^
iFunctionGenerator.h:177:3: warning: ignoring return value of 'ssize_t write(int, const void*, size_t)', declared with attribute warn_unused_result [-Wunused-result]
   write(fd, &std_vector[0], size*sizeof(decltype(std_vector.back())));
   ^
iFunctionGenerator.h: In function 'void saftlib::read_vector_from_pipe(int, T&) [with T = std::vector<short int>]':
iFunctionGenerator.h:190:3: warning: ignoring return value of 'ssize_t read(int, void*, size_t)', declared with attribute warn_unused_result [-Wunused-result]
   read(fd, &size, sizeof(guint32));
   ^
iFunctionGenerator.h:192:3: warning: ignoring return value of 'ssize_t read(int, void*, size_t)', declared with attribute warn_unused_result [-Wunused-result]
   read(fd, &std_vector[0], size*sizeof(decltype(std_vector.back())));      
   ^
iFunctionGenerator.h: In function 'void saftlib::read_vector_from_pipe(int, T&) [with T = std::vector<int>]':
iFunctionGenerator.h:190:3: warning: ignoring return value of 'ssize_t read(int, void*, size_t)', declared with attribute warn_unused_result [-Wunused-result]
   read(fd, &size, sizeof(guint32));
   ^
iFunctionGenerator.h:192:3: warning: ignoring return value of 'ssize_t read(int, void*, size_t)', declared with attribute warn_unused_result [-Wunused-result]
   read(fd, &std_vector[0], size*sizeof(decltype(std_vector.back())));      
   ^
iFunctionGenerator.h: In function 'void saftlib::read_vector_from_pipe(int, T&) [with T = std::vector<unsigned char>]':
iFunctionGenerator.h:190:3: warning: ignoring return value of 'ssize_t read(int, void*, size_t)', declared with attribute warn_unused_result [-Wunused-result]
   read(fd, &size, sizeof(guint32));
   ^
iFunctionGenerator.h:192:3: warning: ignoring return value of 'ssize_t read(int, void*, size_t)', declared with attribute warn_unused_result [-Wunused-result]
   read(fd, &std_vector[0], size*sizeof(decltype(std_vector.back())));      
   ^
iMasterFunctionGenerator.cpp: In member function 'bool saftlib::iMasterFunctionGenerator_Proxy::AppendParameterSets(const std::vector<std::vector<short int> >&, const std::vector<std::vector<short int> >&, const std::vector<std::vector<int> >&, const std::vector<std::vector<unsigned char> >&, const std::vector<std::vector<unsigned char> >&, const std::vector<std::vector<unsigned char> >&, const std::vector<std::vector<unsigned char> >&, bool, bool)':
iMasterFunctionGenerator.cpp:110:36: warning: ignoring return value of 'int pipe(int*)', declared with attribute warn_unused_result [-Wunused-result]
   /*int r =*/ pipe(_vector_pipe_fd);
                                    ^
In file included from iMasterFunctionGenerator.cpp:6:0:
iMasterFunctionGenerator.h: In function 'void saftlib::write_vector_to_pipe(int, const std::vector<std::vector<T>, std::allocator<std::vector<T> > >&) [with T = short int]':
iMasterFunctionGenerator.h:196:3: warning: ignoring return value of 'ssize_t write(int, const void*, size_t)', declared with attribute warn_unused_result [-Wunused-result]
   write(fd, &size, sizeof(guint32));
   ^
iMasterFunctionGenerator.h: In function 'void saftlib::write_vector_to_pipe(int, const T&) [with T = std::vector<short int>]':
iMasterFunctionGenerator.h:190:3: warning: ignoring return value of 'ssize_t write(int, const void*, size_t)', declared with attribute warn_unused_result [-Wunused-result]
   write(fd, &size, sizeof(guint32));
   ^
iMasterFunctionGenerator.h:191:3: warning: ignoring return value of 'ssize_t write(int, const void*, size_t)', declared with attribute warn_unused_result [-Wunused-result]
   write(fd, &std_vector[0], size*sizeof(decltype(std_vector.back())));
   ^
iMasterFunctionGenerator.h: In function 'void saftlib::write_vector_to_pipe(int, const std::vector<std::vector<T>, std::allocator<std::vector<T> > >&) [with T = int]':
iMasterFunctionGenerator.h:196:3: warning: ignoring return value of 'ssize_t write(int, const void*, size_t)', declared with attribute warn_unused_result [-Wunused-result]
   write(fd, &size, sizeof(guint32));
   ^
iMasterFunctionGenerator.h: In function 'void saftlib::write_vector_to_pipe(int, const T&) [with T = std::vector<int>]':
iMasterFunctionGenerator.h:190:3: warning: ignoring return value of 'ssize_t write(int, const void*, size_t)', declared with attribute warn_unused_result [-Wunused-result]
   write(fd, &size, sizeof(guint32));
   ^
iMasterFunctionGenerator.h:191:3: warning: ignoring return value of 'ssize_t write(int, const void*, size_t)', declared with attribute warn_unused_result [-Wunused-result]
   write(fd, &std_vector[0], size*sizeof(decltype(std_vector.back())));
   ^
iMasterFunctionGenerator.h: In function 'void saftlib::write_vector_to_pipe(int, const std::vector<std::vector<T>, std::allocator<std::vector<T> > >&) [with T = unsigned char]':
iMasterFunctionGenerator.h:196:3: warning: ignoring return value of 'ssize_t write(int, const void*, size_t)', declared with attribute warn_unused_result [-Wunused-result]
   write(fd, &size, sizeof(guint32));
   ^
iMasterFunctionGenerator.h: In function 'void saftlib::write_vector_to_pipe(int, const T&) [with T = std::vector<unsigned char>]':
iMasterFunctionGenerator.h:190:3: warning: ignoring return value of 'ssize_t write(int, const void*, size_t)', declared with attribute warn_unused_result [-Wunused-result]
   write(fd, &size, sizeof(guint32));
   ^
iMasterFunctionGenerator.h:191:3: warning: ignoring return value of 'ssize_t write(int, const void*, size_t)', declared with attribute warn_unused_result [-Wunused-result]
   write(fd, &std_vector[0], size*sizeof(decltype(std_vector.back())));
   ^
iMasterFunctionGenerator.h: In function 'void saftlib::read_vector_from_pipe(int, std::vector<std::vector<T>, std::allocator<std::vector<T> > >&) [with T = short int]':
iMasterFunctionGenerator.h:211:3: warning: ignoring return value of 'ssize_t read(int, void*, size_t)', declared with attribute warn_unused_result [-Wunused-result]
   read(fd, &size, sizeof(guint32));
   ^
iMasterFunctionGenerator.h: In function 'void saftlib::read_vector_from_pipe(int, T&) [with T = std::vector<short int>]':
iMasterFunctionGenerator.h:204:3: warning: ignoring return value of 'ssize_t read(int, void*, size_t)', declared with attribute warn_unused_result [-Wunused-result]
   read(fd, &size, sizeof(guint32));
   ^
iMasterFunctionGenerator.h:206:3: warning: ignoring return value of 'ssize_t read(int, void*, size_t)', declared with attribute warn_unused_result [-Wunused-result]
   read(fd, &std_vector[0], size*sizeof(decltype(std_vector.back())));      
   ^
iMasterFunctionGenerator.h: In function 'void saftlib::read_vector_from_pipe(int, std::vector<std::vector<T>, std::allocator<std::vector<T> > >&) [with T = int]':
iMasterFunctionGenerator.h:211:3: warning: ignoring return value of 'ssize_t read(int, void*, size_t)', declared with attribute warn_unused_result [-Wunused-result]
   read(fd, &size, sizeof(guint32));
   ^
iMasterFunctionGenerator.h: In function 'void saftlib::read_vector_from_pipe(int, T&) [with T = std::vector<int>]':
iMasterFunctionGenerator.h:204:3: warning: ignoring return value of 'ssize_t read(int, void*, size_t)', declared with attribute warn_unused_result [-Wunused-result]
   read(fd, &size, sizeof(guint32));
   ^
iMasterFunctionGenerator.h:206:3: warning: ignoring return value of 'ssize_t read(int, void*, size_t)', declared with attribute warn_unused_result [-Wunused-result]
   read(fd, &std_vector[0], size*sizeof(decltype(std_vector.back())));      
   ^
iMasterFunctionGenerator.h: In function 'void saftlib::read_vector_from_pipe(int, std::vector<std::vector<T>, std::allocator<std::vector<T> > >&) [with T = unsigned char]':
iMasterFunctionGenerator.h:211:3: warning: ignoring return value of 'ssize_t read(int, void*, size_t)', declared with attribute warn_unused_result [-Wunused-result]
   read(fd, &size, sizeof(guint32));
   ^
iMasterFunctionGenerator.h: In function 'void saftlib::read_vector_from_pipe(int, T&) [with T = std::vector<unsigned char>]':
iMasterFunctionGenerator.h:204:3: warning: ignoring return value of 'ssize_t read(int, void*, size_t)', declared with attribute warn_unused_result [-Wunused-result]
   read(fd, &size, sizeof(guint32));
   ^
iMasterFunctionGenerator.h:206:3: warning: ignoring return value of 'ssize_t read(int, void*, size_t)', declared with attribute warn_unused_result [-Wunused-result]
   read(fd, &std_vector[0], size*sizeof(decltype(std_vector.back())));

**Comment by alex-cscotg** [comment]
Additional information: $g++ --version
g++  4.8.4

**Comment by miree** [comment]
I'll fix it

**Comment by alex-cscotg** [comment]
Fixed with commit 625a5ef3ffe86758a1460d53374487a274aaf31a and pull request #22
