### ISSUE TITLE
unable to start saftlib on scu2 with RH6

### ISSUE THREAD

**Issue by dietrichb** [GSI-CS-CO/saftlib#3]
The gateware build is from 19 July 2016
The Saftlib branch has been created from proposed master on  19-July-2016

So everything should be up to date...
Maybe the top file or monster is not up to date for SCU2?

Error Message
============
Attaching baseboard(dev/wbm0): Glib::Error: AttachDevice: failed to open: Device::enable_msi: system failure

gateware
=======
Project     : scu_control
Platform    : scu2 +comexpress +wrex1
FPGA model  : Arria II GX (EP2AGX125EF29C5)
Source info : zenith-1241
Build type  : developer preview
Build date  : Tue Jul 19 04:03:13 CEST 2016
Prepared by : jenkins <csco-tg@gsi.de>
Prepared on : tsl004.acc.gsi.de
OS version  : Debian GNU/Linux 8.5 (jessie), kernel 3.16.0-4-amd64
Quartus     : Version 16.0.0 Build 211 04/27/2016 SJ Standard Edition

  9b62a31 saftlib: updated pointer to a new commit
  adea104 saftlib: updated pointer
  1afce9c scu-sw: cleanup of fg configure function, switch slaves to ext clk
  6ef18eb scu-sw: improved irq handler, less accesses to the scu bus, compile with -O2
  b8e35d7 scu-sw: added messagebox to fg sw

saftlib
=====
[user@host saftlib]$ git log -3
commit a1622c951ef2050172bfa3f01033cf195ac0f5f4
Author: Dietrich Beck <d.beck@gsi.de>
Date:   Wed Jul 20 08:10:07 2016 +0200

    saftlib: updated saft-gmt-check

commit f350d46e33a8098fb729ad36ed42553aea4a1d64
Author: Dietrich Beck <d.beck@gsi.de>
Date:   Tue Jul 19 12:08:43 2016 +0200

    minor changes

commit e1089db08e759309ed12f1de51dbfb62319750c5
Author: Dietrich Beck <d.beck@gsi.de>
Date:   Tue Jul 19 12:07:50 2016 +0200

    added saft-gmt-check
[dbeck@asl732 saftlib]$ git log -10
commit a1622c951ef2050172bfa3f01033cf195ac0f5f4
Author: Dietrich Beck <d.beck@gsi.de>
Date:   Wed Jul 20 08:10:07 2016 +0200

    saftlib: updated saft-gmt-check

commit f350d46e33a8098fb729ad36ed42553aea4a1d64
Author: Dietrich Beck <d.beck@gsi.de>
Date:   Tue Jul 19 12:08:43 2016 +0200

    minor changes

commit e1089db08e759309ed12f1de51dbfb62319750c5
Author: Dietrich Beck <d.beck@gsi.de>
Date:   Tue Jul 19 12:07:50 2016 +0200

    added saft-gmt-check

commit 0eae694b8338d98553d8297cd53a497e34895d77
Author: Dietrich Beck <d.beck@gsi.de>
Date:   Tue Jul 19 10:59:23 2016 +0200

    saftlib: saft-dm supports iterations of schedules

commit 1cef93b01f0d1dae9780758dcb89ddae7cb72797
Author: A. Hahn <a.hahn@gsi.de>
Date:   Tue Jul 19 09:58:11 2016 +0200

    saft-tools: unified help messages

commit e591e36264c60ca930bd5462c5e5549203672ba9
Author: A. Hahn <a.hahn@gsi.de>
Date:   Tue Jul 19 09:49:48 2016 +0200

    saft-io-ctl: added translate mask feature

commit 93e3f0690905ef6afc946c153a4f4529d25dd956
Author: A. Hahn <a.hahn@gsi.de>
Date:   Tue Jul 19 09:27:15 2016 +0200

    saft-clk-gen: changed frequency argument to double

commit 0e3f26f7cc576b64d7af567bb3b4a5b3090ede57
Author: A. Hahn <a.hahn@gsi.de>
Date:   Mon Jul 18 16:17:18 2016 +0200

    saft-ecpu-ctl: added translate mask feature and listing option

commit a8e3e6c0f338e3c4b727e2d8e692771042561766
Author: A. Hahn <a.hahn@gsi.de>
Date:   Mon Jul 18 15:41:11 2016 +0200

    saft-ecpu-ctl: added segfault protection for ambiguous arguments

commit 99401ffa706a8b1e77ad34f4ea2df968f45a6e6e
Author: A. Hahn <a.hahn@gsi.de>
Date:   Mon Jul 18 15:17:39 2016 +0200

    saft-io-ctl: added segfault protection for ambiguous arguments

...

**Comment by dietrichb** [comment]
Update: On SCU3 it works, so the issue is only there for SCU2

**Comment by alex-cscotg** [comment]
Still unable to reproduce. We will check that with RH7 again.

**Comment by dietrichb** [comment]
SCU migrated to Centos7
- scuxl0133 -> scuxl.el7
- 30_etherbone-dev -> ../global/etherbone-rc8
- 40_saftlib-dev -> ../global/saftlib-rc8

This works out of the box. As it was decided to discontinue the support for RH6 with the upcoming release, this issue is closed.
