### ISSUE TITLE
[minor] API to get current UTC-TAI offset

### ISSUE THREAD

**Issue by alexxcons** [GSI-CS-CO/saftlib#60]
If I get a WR TAI stamp (e.g. directly from some etherbone device),  currently I need to do "saftlib::TimingReceiver_Proxy::CurrentTime()"  on the saftlib, and than compare the UTC and TAI stamp of that time to get the current UTC-TAI diff.

D.Day told me there already is a method to just get the UTC-TAI diff, but its not public API ?
If so, it would be nice to have it public API.

**Comment by miree** [comment]
Saftlib 2.0 has a type "saftlib::Time" that can be used for this using the member function
  int64_t saftlib::Time::getUTCOffset()
or alternatively the more C-like function
  int64_t saftlib::UTC_offset_TAI(uint64_t TAI);

Any uint64_t that represents a TAI value can be converted to saftlib::Time using the function 
   saftlib::Time saftlib::makeTimeTAI(uint64_t TAI)

example:
uint64_t tai_timestamp_from_eb_device = /*...*/;
int64_t offset = saftlib::makeTimeTAI(tai_timestamp_from_eb_device).getUTCOffset();
// or alternatively
int64_t offset = saftlib::UTC_offset_TAI(tai_timestamp_from_eb_device);

These functions do not require any hardware access.

**Comment by alexxcons** [comment]
Thanks for the code snippets ! I'll take a try next week .. will close the bug than.
