### ISSUE TITLE
No event is shown by 'snoop' when multiple devices are attached

### ISSUE THREAD

**Issue by ebold-cscotos** [GSI-CS-CO/saftlib#77]
Locally injected timing events are not shown by 'snoop' command of saft-ctl for a given timing receiver, when there are multiple devices are attached to the SAFT daemon.

saftlib version:
```
$ saft-ctl bla -i
saftlib source version                  : saftlib 2.2.5 (v2.2.5): Nov 02 2020 11:38:59
saftlib build info                      : built by xxx on Feb 18 2021 18:05:21 with acopc017 running Linux Mint 19.1 Tessa
```

# Setup

Two devices are attached via **PCIe** to saftd:
- dev/wbm0 (Pexaria)
- dev/wbm2 (Pexp)

```
$ sudo saft-ctl bla -j
devices attached on this host   : 2
  device: /de/gsi/saftlib/fbasrx, name: fbasrx, path: dev/wbm2, gatewareVersion : 6.0.1
  --gateware version info:
  ---- Tue Nov 03 10:03:43 CET 2020
  ---- fallout-v6.0.1
  ---- Arria V (5agxma3d4f27i3)
  ---- CentOS Linux release 7.8.2003 (Core), kernel 3.10.0-1127.18.2.el7.x86_64
  ---- pexp
  ---- Timing Group Jenkins <csco-tg@gsi.de>
  ---- tsl021.acc.gsi.de
  ---- pexp_control
  ---- Version 18.1.0 Build 625 09/12/2018 SJ Standard Edition
  ---- fallout-3301

  device: /de/gsi/saftlib/fbastx, name: fbastx, path: dev/wbm0, gatewareVersion : 6.0.1
  --gateware version info:
  ---- Tue Nov 03 08:48:31 CET 2020
  ---- fallout-v6.0.1
  ---- Arria V (5agxma3d4f27i3)
  ---- CentOS Linux release 7.8.2003 (Core), kernel 3.10.0-1127.18.2.el7.x86_64
  ---- pexaria5 +db[12] +wrex1
  ---- Timing Group Jenkins <csco-tg@gsi.de>
  ---- tsl021.acc.gsi.de
  ---- pci_control
  ---- Version 18.1.0 Build 625 09/12/2018 SJ Standard Edition
  ---- fallout-3301

Device 'bla' does not exist
```

# Re-produce the problem

ECA rule is set for one timing receiver, i.e., **fbastx**:

```
$ saft-ecpu-ctl fbastx -l
/de/gsi/saftlib/fbastx/embedded_cpu/_1957747793:
  Event ID: 0xffffeeee00000000
  Mask:     0xffffffff00000000
  Tag:      0x42
  Offset:   0
  Owner:    
```

If an expected timing event is injected to **fbastx** locally, then 'snoop' command on the second terminal will not present this event!

```
$ saft-ctl fbastx snoop 0 0 0   # launch it at the 2nd terminal before injecting a timing event to fbastx locally
$ saft-ctl fbastx -fp inject 0xffffeeee00000000 0x0 1000000   # no event is seen by 'snoop' at the 2nd terminal
```

If the same event is injected again after removal of other timing receiver (i.e., **fbasrx**), then 'snoop' starts to present the injected events:
```
$ saft-ctl fbasrx remove    # remove 'fbasrx' and keep 'fbastx'
$ saft-ctl fbastx -fp inject 0xffffeeee00000000 0x0 1000000   # now this event is presented by 'snoop' at the 2nd terminal
```

**Comment by dietrichb** [comment]
Strange... I have multiple receivers (up to 3) attached to the same saftd at about 5-6 system and no issues.

I can snoop simultaneously on both TR, it works.

I suspect the following issue in your case: You have two physically distinct TRs. If you inject an event locally into ONE of those TR, it is of course only processed by the ECA of the physical hardware that the event was injected to.

**Comment by ebold-cscotos** [comment]
You're right. The '-f' option was overlooked here: it tells saftd to use the first attached device (and ignore <device name>).
Without it 'snoop' works as expected. Thanks!
